spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/security-login
    username: test
    password: test

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  jackson:
    mapper:
      accept-case-insensitive-enums: true

jwt:
  secret-key: 68576D5A7134743777217A25432A462D4A404E635266556A586E327235753878
  expiration: 86400000